apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: kubesphere-monitoring-system
type: Opaque
data:
  username: cm9vdA==
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Service
metadata:
  name: alerting-db
  namespace: kubesphere-monitoring-system
  labels:
    app: alerting
    tier: db
    version: v1.0.0
spec:
  selector:
    app: alerting
    tier: db
  ports:
  - name: tcp
    protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alerting-db-pvc
  namespace: kubesphere-monitoring-system
  labels:
    app: alerting
    tier: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: alerting-db-deployment
  namespace: kubesphere-monitoring-system
  labels:
    app: alerting
    tier: db
    version: v1.0.0
spec:
  selector:
    matchLabels:
      app: alerting
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alerting
        tier: db
        version: v1.0.0
    spec:
      containers:
      - name: alerting-db
        image: mysql:8.0.11
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command: ["sh", "-c", "rm -rf /var/lib/mysql/lost+found"]
        args:
          - --default-authentication-plugin=mysql_native_password
          - --binlog-expire-logs-seconds=604800
          - --max-binlog-size=1073741824
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: db-secret
        - name: MYSQL_ROOT_HOST
          value: "%"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: db-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: db-persistent-storage
        persistentVolumeClaim:
          claimName: alerting-db-pvc
