// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alertrule.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// alert rule
type AlertRule struct {
	AlertRuleId       string      `protobuf:"bytes,1,opt,name=alert_rule_id" json:"alert_rule_id,omitempty"`
	AlertRuleName     string      `protobuf:"bytes,2,opt,name=alert_rule_name" json:"alert_rule_name,omitempty"`
	RepeatSend        *RepeatSend `protobuf:"bytes,3,opt,name=repeat_send" json:"repeat_send,omitempty"`
	ConsecutiveCount  int32       `protobuf:"varint,4,opt,name=consecutive_count" json:"consecutive_count,omitempty"`
	Period            int32       `protobuf:"varint,5,opt,name=period" json:"period,omitempty"`
	ConditionType     string      `protobuf:"bytes,6,opt,name=condition_type" json:"condition_type,omitempty"`
	Threshold         float32     `protobuf:"fixed32,7,opt,name=threshold" json:"threshold,omitempty"`
	Unit              string      `protobuf:"bytes,8,opt,name=unit" json:"unit,omitempty"`
	PreferSeverity    bool        `protobuf:"varint,9,opt,name=prefer_severity" json:"prefer_severity,omitempty"`
	Enable            bool        `protobuf:"varint,10,opt,name=enable" json:"enable,omitempty"`
	InhibitRuleEnable bool        `protobuf:"varint,11,opt,name=inhibit_rule_enable" json:"inhibit_rule_enable,omitempty"`
	MetricId          string      `protobuf:"bytes,12,opt,name=metric_id" json:"metric_id,omitempty"`
	MetricName        string      `protobuf:"bytes,13,opt,name=metric_name" json:"metric_name,omitempty"`
	RefAlertRuleId    string      `protobuf:"bytes,14,opt,name=ref_alert_rule_id" json:"ref_alert_rule_id,omitempty"`
}

func (m *AlertRule) Reset()                    { *m = AlertRule{} }
func (m *AlertRule) String() string            { return proto.CompactTextString(m) }
func (*AlertRule) ProtoMessage()               {}
func (*AlertRule) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *AlertRule) GetAlertRuleId() string {
	if m != nil {
		return m.AlertRuleId
	}
	return ""
}

func (m *AlertRule) GetAlertRuleName() string {
	if m != nil {
		return m.AlertRuleName
	}
	return ""
}

func (m *AlertRule) GetRepeatSend() *RepeatSend {
	if m != nil {
		return m.RepeatSend
	}
	return nil
}

func (m *AlertRule) GetConsecutiveCount() int32 {
	if m != nil {
		return m.ConsecutiveCount
	}
	return 0
}

func (m *AlertRule) GetPeriod() int32 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *AlertRule) GetConditionType() string {
	if m != nil {
		return m.ConditionType
	}
	return ""
}

func (m *AlertRule) GetThreshold() float32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *AlertRule) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *AlertRule) GetPreferSeverity() bool {
	if m != nil {
		return m.PreferSeverity
	}
	return false
}

func (m *AlertRule) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *AlertRule) GetInhibitRuleEnable() bool {
	if m != nil {
		return m.InhibitRuleEnable
	}
	return false
}

func (m *AlertRule) GetMetricId() string {
	if m != nil {
		return m.MetricId
	}
	return ""
}

func (m *AlertRule) GetMetricName() string {
	if m != nil {
		return m.MetricName
	}
	return ""
}

func (m *AlertRule) GetRefAlertRuleId() string {
	if m != nil {
		return m.RefAlertRuleId
	}
	return ""
}

type AlertRuleGroupSpec struct {
	AlertRuleGroupId string `protobuf:"bytes,1,opt,name=alert_rule_group_id" json:"alert_rule_group_id,omitempty"`
	// list/delete bulid-in alert rules
	ResourceType string `protobuf:"bytes,2,opt,name=resource_type" json:"resource_type,omitempty"`
}

func (m *AlertRuleGroupSpec) Reset()                    { *m = AlertRuleGroupSpec{} }
func (m *AlertRuleGroupSpec) String() string            { return proto.CompactTextString(m) }
func (*AlertRuleGroupSpec) ProtoMessage()               {}
func (*AlertRuleGroupSpec) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *AlertRuleGroupSpec) GetAlertRuleGroupId() string {
	if m != nil {
		return m.AlertRuleGroupId
	}
	return ""
}

func (m *AlertRuleGroupSpec) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

type AlertRuleGroupResponse struct {
	AlertRuleGroup *AlertRuleGroup `protobuf:"bytes,1,opt,name=alert_rule_group" json:"alert_rule_group,omitempty"`
	Error          *Error          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *AlertRuleGroupResponse) Reset()                    { *m = AlertRuleGroupResponse{} }
func (m *AlertRuleGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*AlertRuleGroupResponse) ProtoMessage()               {}
func (*AlertRuleGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *AlertRuleGroupResponse) GetAlertRuleGroup() *AlertRuleGroup {
	if m != nil {
		return m.AlertRuleGroup
	}
	return nil
}

func (m *AlertRuleGroupResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

// alert rule group
type AlertRuleGroup struct {
	ReceiverGroupId   string       `protobuf:"bytes,1,opt,name=receiver_group_id" json:"receiver_group_id,omitempty"`
	ReceiverGroupName string       `protobuf:"bytes,2,opt,name=receiver_group_name" json:"receiver_group_name,omitempty"`
	Desc              string       `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	AlertRules        []*AlertRule `protobuf:"bytes,4,rep,name=alert_rules" json:"alert_rules,omitempty"`
}

func (m *AlertRuleGroup) Reset()                    { *m = AlertRuleGroup{} }
func (m *AlertRuleGroup) String() string            { return proto.CompactTextString(m) }
func (*AlertRuleGroup) ProtoMessage()               {}
func (*AlertRuleGroup) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *AlertRuleGroup) GetReceiverGroupId() string {
	if m != nil {
		return m.ReceiverGroupId
	}
	return ""
}

func (m *AlertRuleGroup) GetReceiverGroupName() string {
	if m != nil {
		return m.ReceiverGroupName
	}
	return ""
}

func (m *AlertRuleGroup) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *AlertRuleGroup) GetAlertRules() []*AlertRule {
	if m != nil {
		return m.AlertRules
	}
	return nil
}

func init() {
	proto.RegisterType((*AlertRule)(nil), "pb.AlertRule")
	proto.RegisterType((*AlertRuleGroupSpec)(nil), "pb.AlertRuleGroupSpec")
	proto.RegisterType((*AlertRuleGroupResponse)(nil), "pb.AlertRuleGroupResponse")
	proto.RegisterType((*AlertRuleGroup)(nil), "pb.AlertRuleGroup")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AlertRuleHandler service

type AlertRuleHandlerClient interface {
	// alert rule
	CreateAlertRule(ctx context.Context, in *AlertRuleGroup, opts ...grpc.CallOption) (*AlertRuleGroupResponse, error)
	DeleteAlertRule(ctx context.Context, in *AlertRuleGroupSpec, opts ...grpc.CallOption) (*AlertRuleGroupResponse, error)
	UpdateAlertRule(ctx context.Context, in *AlertRuleGroup, opts ...grpc.CallOption) (*AlertRuleGroupResponse, error)
	GetAlertRule(ctx context.Context, in *AlertRuleGroupSpec, opts ...grpc.CallOption) (*AlertRuleGroupResponse, error)
}

type alertRuleHandlerClient struct {
	cc *grpc.ClientConn
}

func NewAlertRuleHandlerClient(cc *grpc.ClientConn) AlertRuleHandlerClient {
	return &alertRuleHandlerClient{cc}
}

func (c *alertRuleHandlerClient) CreateAlertRule(ctx context.Context, in *AlertRuleGroup, opts ...grpc.CallOption) (*AlertRuleGroupResponse, error) {
	out := new(AlertRuleGroupResponse)
	err := grpc.Invoke(ctx, "/pb.AlertRuleHandler/CreateAlertRule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertRuleHandlerClient) DeleteAlertRule(ctx context.Context, in *AlertRuleGroupSpec, opts ...grpc.CallOption) (*AlertRuleGroupResponse, error) {
	out := new(AlertRuleGroupResponse)
	err := grpc.Invoke(ctx, "/pb.AlertRuleHandler/DeleteAlertRule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertRuleHandlerClient) UpdateAlertRule(ctx context.Context, in *AlertRuleGroup, opts ...grpc.CallOption) (*AlertRuleGroupResponse, error) {
	out := new(AlertRuleGroupResponse)
	err := grpc.Invoke(ctx, "/pb.AlertRuleHandler/UpdateAlertRule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertRuleHandlerClient) GetAlertRule(ctx context.Context, in *AlertRuleGroupSpec, opts ...grpc.CallOption) (*AlertRuleGroupResponse, error) {
	out := new(AlertRuleGroupResponse)
	err := grpc.Invoke(ctx, "/pb.AlertRuleHandler/GetAlertRule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AlertRuleHandler service

type AlertRuleHandlerServer interface {
	// alert rule
	CreateAlertRule(context.Context, *AlertRuleGroup) (*AlertRuleGroupResponse, error)
	DeleteAlertRule(context.Context, *AlertRuleGroupSpec) (*AlertRuleGroupResponse, error)
	UpdateAlertRule(context.Context, *AlertRuleGroup) (*AlertRuleGroupResponse, error)
	GetAlertRule(context.Context, *AlertRuleGroupSpec) (*AlertRuleGroupResponse, error)
}

func RegisterAlertRuleHandlerServer(s *grpc.Server, srv AlertRuleHandlerServer) {
	s.RegisterService(&_AlertRuleHandler_serviceDesc, srv)
}

func _AlertRuleHandler_CreateAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRuleGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertRuleHandlerServer).CreateAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AlertRuleHandler/CreateAlertRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertRuleHandlerServer).CreateAlertRule(ctx, req.(*AlertRuleGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertRuleHandler_DeleteAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRuleGroupSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertRuleHandlerServer).DeleteAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AlertRuleHandler/DeleteAlertRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertRuleHandlerServer).DeleteAlertRule(ctx, req.(*AlertRuleGroupSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertRuleHandler_UpdateAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRuleGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertRuleHandlerServer).UpdateAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AlertRuleHandler/UpdateAlertRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertRuleHandlerServer).UpdateAlertRule(ctx, req.(*AlertRuleGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertRuleHandler_GetAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRuleGroupSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertRuleHandlerServer).GetAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AlertRuleHandler/GetAlertRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertRuleHandlerServer).GetAlertRule(ctx, req.(*AlertRuleGroupSpec))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlertRuleHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AlertRuleHandler",
	HandlerType: (*AlertRuleHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlertRule",
			Handler:    _AlertRuleHandler_CreateAlertRule_Handler,
		},
		{
			MethodName: "DeleteAlertRule",
			Handler:    _AlertRuleHandler_DeleteAlertRule_Handler,
		},
		{
			MethodName: "UpdateAlertRule",
			Handler:    _AlertRuleHandler_UpdateAlertRule_Handler,
		},
		{
			MethodName: "GetAlertRule",
			Handler:    _AlertRuleHandler_GetAlertRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alertrule.proto",
}

func init() { proto.RegisterFile("alertrule.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcb, 0x6e, 0xdb, 0x3c,
	0x10, 0x85, 0x7f, 0x29, 0xb6, 0xff, 0x68, 0xe4, 0x2b, 0x8d, 0xb8, 0x8c, 0xb3, 0x11, 0xd4, 0x8d,
	0x16, 0x85, 0x17, 0xee, 0x13, 0xb4, 0x4e, 0xe1, 0xac, 0x1d, 0x74, 0xd3, 0x8d, 0xaa, 0xcb, 0xa4,
	0x26, 0xa0, 0x90, 0xc4, 0x88, 0x32, 0x90, 0xbe, 0x52, 0x9f, 0xa5, 0xef, 0x54, 0x90, 0x72, 0xe2,
	0x4b, 0x0a, 0x74, 0x91, 0x25, 0xcf, 0x90, 0xdf, 0xcc, 0x39, 0x1a, 0xc1, 0x28, 0xab, 0x90, 0x0c,
	0x35, 0x15, 0x2e, 0x34, 0x29, 0xa3, 0x98, 0xaf, 0xf3, 0x79, 0x88, 0x44, 0x8a, 0x5a, 0x61, 0x3e,
	0x26, 0xd4, 0x98, 0x99, 0x1a, 0x65, 0xd9, 0x2a, 0xf1, 0x6f, 0x1f, 0x82, 0x4f, 0xf6, 0xd9, 0xa6,
	0xa9, 0x90, 0x5d, 0xc1, 0xc0, 0x31, 0x52, 0x0b, 0x49, 0x45, 0xc9, 0xbd, 0xc8, 0x4b, 0x02, 0xf6,
	0x6e, 0x8f, 0x6e, 0x65, 0x99, 0x3d, 0x22, 0xf7, 0x5d, 0xe1, 0x3d, 0x84, 0x2d, 0x31, 0xb5, 0x48,
	0x7e, 0x11, 0x79, 0x49, 0xb8, 0x1c, 0x2e, 0x74, 0xbe, 0xd8, 0x38, 0xf9, 0x1e, 0x65, 0xc9, 0xae,
	0x61, 0x52, 0x28, 0x59, 0x63, 0xd1, 0x18, 0xb1, 0xc3, 0xb4, 0x50, 0x8d, 0x34, 0xbc, 0x13, 0x79,
	0x49, 0x97, 0x0d, 0xa1, 0xa7, 0x91, 0x84, 0x2a, 0x79, 0xd7, 0x9d, 0x67, 0x30, 0x2c, 0x94, 0x2c,
	0x85, 0x11, 0x4a, 0xa6, 0xe6, 0x49, 0x23, 0xef, 0xb9, 0x3e, 0x13, 0x08, 0xcc, 0x96, 0xb0, 0xde,
	0xaa, 0xaa, 0xe4, 0xff, 0x47, 0x5e, 0xe2, 0xb3, 0x3e, 0x74, 0x1a, 0x29, 0x0c, 0xbf, 0x7c, 0x9e,
	0x50, 0x13, 0x3e, 0x20, 0xa5, 0x35, 0xee, 0x90, 0x84, 0x79, 0xe2, 0x41, 0xe4, 0x25, 0x97, 0xb6,
	0x03, 0xca, 0x2c, 0xaf, 0x90, 0x83, 0x3b, 0xdf, 0xc0, 0x54, 0xc8, 0xad, 0xc8, 0xc5, 0xde, 0xcc,
	0xbe, 0x18, 0xba, 0xe2, 0x04, 0x82, 0x47, 0x34, 0x24, 0x0a, 0x6b, 0xbd, 0xef, 0xc0, 0x53, 0x08,
	0xf7, 0x92, 0xb3, 0x3d, 0x70, 0xe2, 0x35, 0x4c, 0x08, 0x1f, 0xd2, 0xd3, 0xa8, 0x86, 0xb6, 0x14,
	0xdf, 0x01, 0x7b, 0x89, 0x73, 0x4d, 0xaa, 0xd1, 0xf7, 0x1a, 0x0b, 0xdb, 0xf5, 0xe8, 0xf2, 0x0f,
	0xab, 0x1f, 0xd2, 0xbd, 0x82, 0x01, 0x61, 0xad, 0x1a, 0x2a, 0xb0, 0xf5, 0xec, 0xb2, 0x8d, 0xbf,
	0xc3, 0xec, 0x94, 0xb4, 0xc1, 0x5a, 0xdb, 0x1c, 0xd9, 0x07, 0x18, 0x9f, 0xd3, 0x1c, 0x2a, 0x5c,
	0x32, 0x1b, 0xfd, 0xe9, 0x2b, 0xc6, 0xa1, 0xeb, 0x56, 0xc0, 0x61, 0xc3, 0x65, 0x60, 0xaf, 0x7c,
	0xb1, 0x42, 0xfc, 0x13, 0x86, 0x67, 0x77, 0x9d, 0xb1, 0x02, 0xc5, 0x0e, 0xe9, 0x7c, 0xca, 0x1b,
	0x98, 0x9e, 0x95, 0x8e, 0xf6, 0xa0, 0x0f, 0x9d, 0x12, 0xeb, 0xc2, 0x2d, 0x40, 0xc0, 0x62, 0x08,
	0x0f, 0xf3, 0xd5, 0xbc, 0x13, 0x5d, 0x24, 0xe1, 0x72, 0x70, 0x32, 0xda, 0xf2, 0x97, 0x0f, 0xe3,
	0x97, 0xd3, 0x5d, 0x26, 0xcb, 0x0a, 0x89, 0xad, 0x60, 0xb4, 0x22, 0xcc, 0x0c, 0x1e, 0x36, 0xf2,
	0x2f, 0x8e, 0xe6, 0xf3, 0xd7, 0xda, 0x73, 0x36, 0xf1, 0x7f, 0x6c, 0x0d, 0xa3, 0x5b, 0xac, 0xf0,
	0x18, 0x32, 0x7b, 0xfd, 0xc0, 0x7e, 0x96, 0x7f, 0x80, 0x56, 0x30, 0xfa, 0xaa, 0xcb, 0x37, 0x4e,
	0x73, 0x0b, 0xfd, 0x35, 0x9a, 0x37, 0x8e, 0xf2, 0xb9, 0xf3, 0xcd, 0xd7, 0x79, 0xde, 0x73, 0xbf,
	0xec, 0xc7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x53, 0x33, 0x1d, 0x0f, 0xe8, 0x03, 0x00, 0x00,
}
