// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ent.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Enterprise struct {
	EnterpriseId   string `protobuf:"bytes,1,opt,name=enterprise_id" json:"enterprise_id,omitempty"`
	EnterpriseName string `protobuf:"bytes,2,opt,name=enterprise_name" json:"enterprise_name,omitempty"`
	HomePage       string `protobuf:"bytes,3,opt,name=home_page" json:"home_page,omitempty"`
	Address        string `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	Phone          string `protobuf:"bytes,5,opt,name=phone" json:"phone,omitempty"`
	Email          string `protobuf:"bytes,6,opt,name=email" json:"email,omitempty"`
	Contacts       string `protobuf:"bytes,7,opt,name=contacts" json:"contacts,omitempty"`
	Desc           string `protobuf:"bytes,8,opt,name=desc" json:"desc,omitempty"`
}

func (m *Enterprise) Reset()                    { *m = Enterprise{} }
func (m *Enterprise) String() string            { return proto.CompactTextString(m) }
func (*Enterprise) ProtoMessage()               {}
func (*Enterprise) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Enterprise) GetEnterpriseId() string {
	if m != nil {
		return m.EnterpriseId
	}
	return ""
}

func (m *Enterprise) GetEnterpriseName() string {
	if m != nil {
		return m.EnterpriseName
	}
	return ""
}

func (m *Enterprise) GetHomePage() string {
	if m != nil {
		return m.HomePage
	}
	return ""
}

func (m *Enterprise) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Enterprise) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Enterprise) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Enterprise) GetContacts() string {
	if m != nil {
		return m.Contacts
	}
	return ""
}

func (m *Enterprise) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type EnterpriseSpec struct {
	EnterpriseId   string `protobuf:"bytes,1,opt,name=enterprise_id" json:"enterprise_id,omitempty"`
	EnterpriseName string `protobuf:"bytes,2,opt,name=enterprise_name" json:"enterprise_name,omitempty"`
}

func (m *EnterpriseSpec) Reset()                    { *m = EnterpriseSpec{} }
func (m *EnterpriseSpec) String() string            { return proto.CompactTextString(m) }
func (*EnterpriseSpec) ProtoMessage()               {}
func (*EnterpriseSpec) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *EnterpriseSpec) GetEnterpriseId() string {
	if m != nil {
		return m.EnterpriseId
	}
	return ""
}

func (m *EnterpriseSpec) GetEnterpriseName() string {
	if m != nil {
		return m.EnterpriseName
	}
	return ""
}

type EnterpriseResponse struct {
	Enterprise *Enterprise `protobuf:"bytes,1,opt,name=enterprise" json:"enterprise,omitempty"`
	Error      *Error      `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *EnterpriseResponse) Reset()                    { *m = EnterpriseResponse{} }
func (m *EnterpriseResponse) String() string            { return proto.CompactTextString(m) }
func (*EnterpriseResponse) ProtoMessage()               {}
func (*EnterpriseResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *EnterpriseResponse) GetEnterprise() *Enterprise {
	if m != nil {
		return m.Enterprise
	}
	return nil
}

func (m *EnterpriseResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Enterprise)(nil), "pb.Enterprise")
	proto.RegisterType((*EnterpriseSpec)(nil), "pb.EnterpriseSpec")
	proto.RegisterType((*EnterpriseResponse)(nil), "pb.EnterpriseResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EnterpriseHandler service

type EnterpriseHandlerClient interface {
	// enterprise
	CreateEnterprise(ctx context.Context, in *Enterprise, opts ...grpc.CallOption) (*EnterpriseResponse, error)
	DeleteEnterprise(ctx context.Context, in *EnterpriseSpec, opts ...grpc.CallOption) (*EnterpriseResponse, error)
	UpdateEnterprise(ctx context.Context, in *Enterprise, opts ...grpc.CallOption) (*EnterpriseResponse, error)
	GetEnterprise(ctx context.Context, in *EnterpriseSpec, opts ...grpc.CallOption) (*EnterpriseResponse, error)
}

type enterpriseHandlerClient struct {
	cc *grpc.ClientConn
}

func NewEnterpriseHandlerClient(cc *grpc.ClientConn) EnterpriseHandlerClient {
	return &enterpriseHandlerClient{cc}
}

func (c *enterpriseHandlerClient) CreateEnterprise(ctx context.Context, in *Enterprise, opts ...grpc.CallOption) (*EnterpriseResponse, error) {
	out := new(EnterpriseResponse)
	err := grpc.Invoke(ctx, "/pb.EnterpriseHandler/CreateEnterprise", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseHandlerClient) DeleteEnterprise(ctx context.Context, in *EnterpriseSpec, opts ...grpc.CallOption) (*EnterpriseResponse, error) {
	out := new(EnterpriseResponse)
	err := grpc.Invoke(ctx, "/pb.EnterpriseHandler/DeleteEnterprise", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseHandlerClient) UpdateEnterprise(ctx context.Context, in *Enterprise, opts ...grpc.CallOption) (*EnterpriseResponse, error) {
	out := new(EnterpriseResponse)
	err := grpc.Invoke(ctx, "/pb.EnterpriseHandler/UpdateEnterprise", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseHandlerClient) GetEnterprise(ctx context.Context, in *EnterpriseSpec, opts ...grpc.CallOption) (*EnterpriseResponse, error) {
	out := new(EnterpriseResponse)
	err := grpc.Invoke(ctx, "/pb.EnterpriseHandler/GetEnterprise", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EnterpriseHandler service

type EnterpriseHandlerServer interface {
	// enterprise
	CreateEnterprise(context.Context, *Enterprise) (*EnterpriseResponse, error)
	DeleteEnterprise(context.Context, *EnterpriseSpec) (*EnterpriseResponse, error)
	UpdateEnterprise(context.Context, *Enterprise) (*EnterpriseResponse, error)
	GetEnterprise(context.Context, *EnterpriseSpec) (*EnterpriseResponse, error)
}

func RegisterEnterpriseHandlerServer(s *grpc.Server, srv EnterpriseHandlerServer) {
	s.RegisterService(&_EnterpriseHandler_serviceDesc, srv)
}

func _EnterpriseHandler_CreateEnterprise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Enterprise)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseHandlerServer).CreateEnterprise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EnterpriseHandler/CreateEnterprise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseHandlerServer).CreateEnterprise(ctx, req.(*Enterprise))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseHandler_DeleteEnterprise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterpriseSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseHandlerServer).DeleteEnterprise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EnterpriseHandler/DeleteEnterprise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseHandlerServer).DeleteEnterprise(ctx, req.(*EnterpriseSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseHandler_UpdateEnterprise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Enterprise)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseHandlerServer).UpdateEnterprise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EnterpriseHandler/UpdateEnterprise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseHandlerServer).UpdateEnterprise(ctx, req.(*Enterprise))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseHandler_GetEnterprise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterpriseSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseHandlerServer).GetEnterprise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EnterpriseHandler/GetEnterprise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseHandlerServer).GetEnterprise(ctx, req.(*EnterpriseSpec))
	}
	return interceptor(ctx, in, info, handler)
}

var _EnterpriseHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EnterpriseHandler",
	HandlerType: (*EnterpriseHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEnterprise",
			Handler:    _EnterpriseHandler_CreateEnterprise_Handler,
		},
		{
			MethodName: "DeleteEnterprise",
			Handler:    _EnterpriseHandler_DeleteEnterprise_Handler,
		},
		{
			MethodName: "UpdateEnterprise",
			Handler:    _EnterpriseHandler_UpdateEnterprise_Handler,
		},
		{
			MethodName: "GetEnterprise",
			Handler:    _EnterpriseHandler_GetEnterprise_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ent.proto",
}

func init() { proto.RegisterFile("ent.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4e, 0x83, 0x40,
	0x10, 0x87, 0x05, 0xa1, 0x2d, 0x83, 0xb4, 0x74, 0x13, 0x75, 0xd3, 0x93, 0xe1, 0xe4, 0x89, 0x03,
	0x5e, 0x6b, 0xd2, 0xf8, 0x27, 0x7a, 0xae, 0xf1, 0xe2, 0xa5, 0x59, 0xd8, 0x89, 0x25, 0x81, 0xdd,
	0xcd, 0xee, 0x3e, 0x88, 0x4f, 0xe0, 0xb3, 0x1a, 0xd6, 0x54, 0xc0, 0x83, 0x89, 0x3d, 0xfe, 0xbe,
	0x19, 0xbe, 0x19, 0x26, 0x0b, 0x11, 0x0a, 0x9b, 0x2b, 0x2d, 0xad, 0x24, 0xbe, 0x2a, 0x57, 0x31,
	0x6a, 0x2d, 0xf5, 0x37, 0xc8, 0x3e, 0x3d, 0x80, 0x47, 0x61, 0x51, 0x2b, 0x5d, 0x1b, 0x24, 0xe7,
	0x90, 0xe0, 0x4f, 0xda, 0xd5, 0x9c, 0x7a, 0x57, 0xde, 0x75, 0x44, 0x2e, 0x61, 0x31, 0xc0, 0x82,
	0xb5, 0x48, 0x7d, 0x57, 0x58, 0x42, 0xb4, 0x97, 0x2d, 0xee, 0x14, 0x7b, 0x47, 0x7a, 0xea, 0xd0,
	0x02, 0xa6, 0x8c, 0x73, 0x8d, 0xc6, 0xd0, 0xc0, 0x81, 0x04, 0x42, 0xb5, 0x97, 0x02, 0x69, 0x78,
	0x88, 0xd8, 0xb2, 0xba, 0xa1, 0x13, 0x17, 0x53, 0x98, 0x55, 0x52, 0x58, 0x56, 0x59, 0x43, 0xa7,
	0x8e, 0x9c, 0x41, 0xc0, 0xd1, 0x54, 0x74, 0xd6, 0xa5, 0x6c, 0x03, 0xf3, 0x7e, 0xbf, 0x17, 0x85,
	0xd5, 0x7f, 0x77, 0xcc, 0xb6, 0x40, 0x7a, 0xc3, 0x16, 0x8d, 0x92, 0xc2, 0x20, 0xc9, 0x00, 0xfa,
	0x76, 0xa7, 0x88, 0x8b, 0x79, 0xae, 0xca, 0x7c, 0x70, 0x0d, 0x0a, 0xa1, 0xbb, 0x95, 0x13, 0xc5,
	0x45, 0xe4, 0xca, 0x1d, 0x28, 0x3e, 0x7c, 0x58, 0xf6, 0x8d, 0xcf, 0x4c, 0xf0, 0x06, 0x35, 0x59,
	0x43, 0x7a, 0xaf, 0x91, 0x59, 0x1c, 0x38, 0x7e, 0x39, 0x57, 0x17, 0xe3, 0x7c, 0xd8, 0x27, 0x3b,
	0x21, 0x1b, 0x48, 0x1f, 0xb0, 0xc1, 0xd1, 0xd7, 0x64, 0xdc, 0xdd, 0xfd, 0xff, 0x1f, 0x86, 0x35,
	0xa4, 0xaf, 0x8a, 0x1f, 0x3b, 0xff, 0x16, 0x92, 0x27, 0xb4, 0xc7, 0x0e, 0xbf, 0x0b, 0xde, 0x7c,
	0x55, 0x96, 0x13, 0xf7, 0xac, 0x6e, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x84, 0x03, 0x52, 0x4e,
	0x74, 0x02, 0x00, 0x00,
}
