// Code generated by protoc-gen-go. DO NOT EDIT.
// source: receiver.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// receiver group
type ReceiverGroup struct {
	ReceiverGroupId   string      `protobuf:"bytes,1,opt,name=receiver_group_id" json:"receiver_group_id,omitempty"`
	ReceiverGroupName string      `protobuf:"bytes,2,opt,name=receiver_group_name" json:"receiver_group_name,omitempty"`
	Webhook           string      `protobuf:"bytes,3,opt,name=webhook" json:"webhook,omitempty"`
	WebhookEnable     bool        `protobuf:"varint,4,opt,name=webhook_enable" json:"webhook_enable,omitempty"`
	Desc              string      `protobuf:"bytes,5,opt,name=desc" json:"desc,omitempty"`
	Receivers         []*Receiver `protobuf:"bytes,6,rep,name=receivers" json:"receivers,omitempty"`
}

func (m *ReceiverGroup) Reset()                    { *m = ReceiverGroup{} }
func (m *ReceiverGroup) String() string            { return proto.CompactTextString(m) }
func (*ReceiverGroup) ProtoMessage()               {}
func (*ReceiverGroup) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *ReceiverGroup) GetReceiverGroupId() string {
	if m != nil {
		return m.ReceiverGroupId
	}
	return ""
}

func (m *ReceiverGroup) GetReceiverGroupName() string {
	if m != nil {
		return m.ReceiverGroupName
	}
	return ""
}

func (m *ReceiverGroup) GetWebhook() string {
	if m != nil {
		return m.Webhook
	}
	return ""
}

func (m *ReceiverGroup) GetWebhookEnable() bool {
	if m != nil {
		return m.WebhookEnable
	}
	return false
}

func (m *ReceiverGroup) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ReceiverGroup) GetReceivers() []*Receiver {
	if m != nil {
		return m.Receivers
	}
	return nil
}

type Receiver struct {
	ReceiverId   string `protobuf:"bytes,1,opt,name=receiver_id" json:"receiver_id,omitempty"`
	ReceiverName string `protobuf:"bytes,2,opt,name=receiver_name" json:"receiver_name,omitempty"`
	Email        string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone        string `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
	Wechat       string `protobuf:"bytes,5,opt,name=wechat" json:"wechat,omitempty"`
}

func (m *Receiver) Reset()                    { *m = Receiver{} }
func (m *Receiver) String() string            { return proto.CompactTextString(m) }
func (*Receiver) ProtoMessage()               {}
func (*Receiver) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *Receiver) GetReceiverId() string {
	if m != nil {
		return m.ReceiverId
	}
	return ""
}

func (m *Receiver) GetReceiverName() string {
	if m != nil {
		return m.ReceiverName
	}
	return ""
}

func (m *Receiver) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Receiver) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Receiver) GetWechat() string {
	if m != nil {
		return m.Wechat
	}
	return ""
}

type ReceiverGroupSpec struct {
	ReceiverGroupId string `protobuf:"bytes,1,opt,name=receiver_group_id" json:"receiver_group_id,omitempty"`
}

func (m *ReceiverGroupSpec) Reset()                    { *m = ReceiverGroupSpec{} }
func (m *ReceiverGroupSpec) String() string            { return proto.CompactTextString(m) }
func (*ReceiverGroupSpec) ProtoMessage()               {}
func (*ReceiverGroupSpec) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *ReceiverGroupSpec) GetReceiverGroupId() string {
	if m != nil {
		return m.ReceiverGroupId
	}
	return ""
}

type ReceiverGroupResponse struct {
	ReceiverGroup *ReceiverGroup `protobuf:"bytes,1,opt,name=receiver_group" json:"receiver_group,omitempty"`
	Error         *Error         `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *ReceiverGroupResponse) Reset()                    { *m = ReceiverGroupResponse{} }
func (m *ReceiverGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*ReceiverGroupResponse) ProtoMessage()               {}
func (*ReceiverGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *ReceiverGroupResponse) GetReceiverGroup() *ReceiverGroup {
	if m != nil {
		return m.ReceiverGroup
	}
	return nil
}

func (m *ReceiverGroupResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*ReceiverGroup)(nil), "pb.ReceiverGroup")
	proto.RegisterType((*Receiver)(nil), "pb.Receiver")
	proto.RegisterType((*ReceiverGroupSpec)(nil), "pb.ReceiverGroupSpec")
	proto.RegisterType((*ReceiverGroupResponse)(nil), "pb.ReceiverGroupResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ReceiverHandler service

type ReceiverHandlerClient interface {
	// Receiver
	CreateReceiver(ctx context.Context, in *ReceiverGroup, opts ...grpc.CallOption) (*ReceiverGroupResponse, error)
	GetReceiver(ctx context.Context, in *ReceiverGroupSpec, opts ...grpc.CallOption) (*ReceiverGroupResponse, error)
	UpdateReceiver(ctx context.Context, in *ReceiverGroup, opts ...grpc.CallOption) (*ReceiverGroupResponse, error)
	DeleteReceiver(ctx context.Context, in *ReceiverGroupSpec, opts ...grpc.CallOption) (*ReceiverGroupResponse, error)
}

type receiverHandlerClient struct {
	cc *grpc.ClientConn
}

func NewReceiverHandlerClient(cc *grpc.ClientConn) ReceiverHandlerClient {
	return &receiverHandlerClient{cc}
}

func (c *receiverHandlerClient) CreateReceiver(ctx context.Context, in *ReceiverGroup, opts ...grpc.CallOption) (*ReceiverGroupResponse, error) {
	out := new(ReceiverGroupResponse)
	err := grpc.Invoke(ctx, "/pb.ReceiverHandler/CreateReceiver", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiverHandlerClient) GetReceiver(ctx context.Context, in *ReceiverGroupSpec, opts ...grpc.CallOption) (*ReceiverGroupResponse, error) {
	out := new(ReceiverGroupResponse)
	err := grpc.Invoke(ctx, "/pb.ReceiverHandler/GetReceiver", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiverHandlerClient) UpdateReceiver(ctx context.Context, in *ReceiverGroup, opts ...grpc.CallOption) (*ReceiverGroupResponse, error) {
	out := new(ReceiverGroupResponse)
	err := grpc.Invoke(ctx, "/pb.ReceiverHandler/UpdateReceiver", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiverHandlerClient) DeleteReceiver(ctx context.Context, in *ReceiverGroupSpec, opts ...grpc.CallOption) (*ReceiverGroupResponse, error) {
	out := new(ReceiverGroupResponse)
	err := grpc.Invoke(ctx, "/pb.ReceiverHandler/DeleteReceiver", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ReceiverHandler service

type ReceiverHandlerServer interface {
	// Receiver
	CreateReceiver(context.Context, *ReceiverGroup) (*ReceiverGroupResponse, error)
	GetReceiver(context.Context, *ReceiverGroupSpec) (*ReceiverGroupResponse, error)
	UpdateReceiver(context.Context, *ReceiverGroup) (*ReceiverGroupResponse, error)
	DeleteReceiver(context.Context, *ReceiverGroupSpec) (*ReceiverGroupResponse, error)
}

func RegisterReceiverHandlerServer(s *grpc.Server, srv ReceiverHandlerServer) {
	s.RegisterService(&_ReceiverHandler_serviceDesc, srv)
}

func _ReceiverHandler_CreateReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiverGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiverHandlerServer).CreateReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ReceiverHandler/CreateReceiver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiverHandlerServer).CreateReceiver(ctx, req.(*ReceiverGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiverHandler_GetReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiverGroupSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiverHandlerServer).GetReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ReceiverHandler/GetReceiver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiverHandlerServer).GetReceiver(ctx, req.(*ReceiverGroupSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiverHandler_UpdateReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiverGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiverHandlerServer).UpdateReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ReceiverHandler/UpdateReceiver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiverHandlerServer).UpdateReceiver(ctx, req.(*ReceiverGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiverHandler_DeleteReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiverGroupSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiverHandlerServer).DeleteReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ReceiverHandler/DeleteReceiver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiverHandlerServer).DeleteReceiver(ctx, req.(*ReceiverGroupSpec))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReceiverHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ReceiverHandler",
	HandlerType: (*ReceiverHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReceiver",
			Handler:    _ReceiverHandler_CreateReceiver_Handler,
		},
		{
			MethodName: "GetReceiver",
			Handler:    _ReceiverHandler_GetReceiver_Handler,
		},
		{
			MethodName: "UpdateReceiver",
			Handler:    _ReceiverHandler_UpdateReceiver_Handler,
		},
		{
			MethodName: "DeleteReceiver",
			Handler:    _ReceiverHandler_DeleteReceiver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "receiver.proto",
}

func init() { proto.RegisterFile("receiver.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x4f, 0x4f, 0xf2, 0x40,
	0x18, 0xc4, 0xdf, 0x16, 0xca, 0x4b, 0x9f, 0xd2, 0x12, 0x96, 0x60, 0x16, 0x3c, 0x48, 0x7a, 0xc2,
	0x4b, 0x0f, 0xf5, 0x0b, 0xa0, 0x62, 0xf0, 0x8c, 0xf1, 0x62, 0x4c, 0x48, 0xff, 0x3c, 0x11, 0x62,
	0xe9, 0x6e, 0xb6, 0x55, 0xbe, 0x8d, 0x7e, 0x55, 0xd3, 0x6d, 0xb7, 0x82, 0x4d, 0x38, 0xe8, 0xad,
	0x99, 0x9d, 0x99, 0xfc, 0x76, 0xba, 0xe0, 0x08, 0x8c, 0x70, 0xfb, 0x8e, 0xc2, 0xe3, 0x82, 0xe5,
	0x8c, 0xe8, 0x3c, 0x9c, 0x58, 0x28, 0x04, 0xab, 0x04, 0xf7, 0x53, 0x03, 0x7b, 0x55, 0x79, 0x96,
	0x82, 0xbd, 0x71, 0x32, 0x86, 0x81, 0x0a, 0xad, 0x5f, 0x0a, 0x65, 0xbd, 0x8d, 0xa9, 0x36, 0xd5,
	0x66, 0x26, 0x39, 0x87, 0xe1, 0x8f, 0xa3, 0x34, 0xd8, 0x21, 0xd5, 0xe5, 0x61, 0x1f, 0xfe, 0xef,
	0x31, 0xdc, 0x30, 0xf6, 0x4a, 0x5b, 0x52, 0x38, 0x03, 0xa7, 0x12, 0xd6, 0x98, 0x06, 0x61, 0x82,
	0xb4, 0x3d, 0xd5, 0x66, 0x5d, 0xd2, 0x83, 0x76, 0x8c, 0x59, 0x44, 0x0d, 0xe9, 0xba, 0x00, 0x53,
	0x75, 0x66, 0xb4, 0x33, 0x6d, 0xcd, 0x2c, 0xbf, 0xe7, 0xf1, 0xd0, 0x53, 0x50, 0x6e, 0x0c, 0x5d,
	0xf5, 0x4d, 0x86, 0x60, 0xd5, 0x00, 0x35, 0xd5, 0x08, 0xec, 0x5a, 0x3c, 0xe0, 0xb1, 0xc1, 0xc0,
	0x5d, 0xb0, 0x4d, 0x2a, 0x1a, 0x1b, 0x0c, 0xbe, 0x61, 0x69, 0x09, 0x61, 0x12, 0x07, 0x3a, 0x7b,
	0x8c, 0x36, 0x41, 0x5e, 0x62, 0xb8, 0x1e, 0x0c, 0x8e, 0x66, 0x78, 0xe0, 0x18, 0x9d, 0x98, 0xc2,
	0x7d, 0x86, 0xd1, 0x91, 0x7f, 0x85, 0x19, 0x67, 0x69, 0x86, 0xe4, 0xf2, 0x7b, 0xf3, 0x32, 0x23,
	0x03, 0x96, 0x3f, 0x38, 0xbc, 0x54, 0xb9, 0x34, 0x05, 0x43, 0xfe, 0x0a, 0x09, 0x6c, 0xf9, 0x66,
	0xe1, 0xb8, 0x2b, 0x04, 0xff, 0x43, 0x87, 0xbe, 0xf2, 0xde, 0x07, 0x69, 0x9c, 0xa0, 0x20, 0x73,
	0x70, 0x6e, 0x05, 0x06, 0x39, 0xd6, 0x6b, 0x34, 0x2b, 0x27, 0xe3, 0x86, 0xa4, 0xc0, 0xdc, 0x7f,
	0xe4, 0x1a, 0xac, 0x25, 0xe6, 0x75, 0x7c, 0xd4, 0xf0, 0x16, 0x97, 0x3e, 0x5d, 0x31, 0x07, 0xe7,
	0x91, 0xc7, 0x7f, 0x81, 0x58, 0x80, 0xb3, 0xc0, 0x04, 0x0f, 0x1a, 0x7e, 0xc1, 0x71, 0xd3, 0x7e,
	0xd2, 0x79, 0x18, 0x76, 0xe4, 0x1b, 0xbe, 0xfa, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x17, 0x5a,
	0xf6, 0xe6, 0x02, 0x00, 0x00,
}
