// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// resource group
type ResourceGroup struct {
	ResourceGroupId      string            `protobuf:"bytes,1,opt,name=resource_group_id,json=resourceGroupId,proto3" json:"resource_group_id,omitempty"`
	ResourceGroupName    string            `protobuf:"bytes,2,opt,name=resource_group_name,json=resourceGroupName,proto3" json:"resource_group_name,omitempty"`
	ResourceUriTmpls     *ResourceUriTmpls `protobuf:"bytes,3,opt,name=resource_uri_tmpls,json=resourceUriTmpls,proto3" json:"resource_uri_tmpls,omitempty"`
	Desc                 string            `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	ResourceTypeId       string            `protobuf:"bytes,5,opt,name=resource_type_id,json=resourceTypeId,proto3" json:"resource_type_id,omitempty"`
	Resources            []*Resource       `protobuf:"bytes,6,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResourceGroup) Reset()         { *m = ResourceGroup{} }
func (m *ResourceGroup) String() string { return proto.CompactTextString(m) }
func (*ResourceGroup) ProtoMessage()    {}
func (*ResourceGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{0}
}

func (m *ResourceGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceGroup.Unmarshal(m, b)
}
func (m *ResourceGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceGroup.Marshal(b, m, deterministic)
}
func (m *ResourceGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceGroup.Merge(m, src)
}
func (m *ResourceGroup) XXX_Size() int {
	return xxx_messageInfo_ResourceGroup.Size(m)
}
func (m *ResourceGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceGroup proto.InternalMessageInfo

func (m *ResourceGroup) GetResourceGroupId() string {
	if m != nil {
		return m.ResourceGroupId
	}
	return ""
}

func (m *ResourceGroup) GetResourceGroupName() string {
	if m != nil {
		return m.ResourceGroupName
	}
	return ""
}

func (m *ResourceGroup) GetResourceUriTmpls() *ResourceUriTmpls {
	if m != nil {
		return m.ResourceUriTmpls
	}
	return nil
}

func (m *ResourceGroup) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ResourceGroup) GetResourceTypeId() string {
	if m != nil {
		return m.ResourceTypeId
	}
	return ""
}

func (m *ResourceGroup) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type ResourceGroupSpec struct {
	ResourceGroupId      string   `protobuf:"bytes,1,opt,name=resource_group_id,json=resourceGroupId,proto3" json:"resource_group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceGroupSpec) Reset()         { *m = ResourceGroupSpec{} }
func (m *ResourceGroupSpec) String() string { return proto.CompactTextString(m) }
func (*ResourceGroupSpec) ProtoMessage()    {}
func (*ResourceGroupSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{1}
}

func (m *ResourceGroupSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceGroupSpec.Unmarshal(m, b)
}
func (m *ResourceGroupSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceGroupSpec.Marshal(b, m, deterministic)
}
func (m *ResourceGroupSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceGroupSpec.Merge(m, src)
}
func (m *ResourceGroupSpec) XXX_Size() int {
	return xxx_messageInfo_ResourceGroupSpec.Size(m)
}
func (m *ResourceGroupSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceGroupSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceGroupSpec proto.InternalMessageInfo

func (m *ResourceGroupSpec) GetResourceGroupId() string {
	if m != nil {
		return m.ResourceGroupId
	}
	return ""
}

type Resource struct {
	ResourceId           string   `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceName         string   `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceGroupId      string   `protobuf:"bytes,3,opt,name=resource_group_id,json=resourceGroupId,proto3" json:"resource_group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{2}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *Resource) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *Resource) GetResourceGroupId() string {
	if m != nil {
		return m.ResourceGroupId
	}
	return ""
}

type ResourceGroupResponse struct {
	ResourceGroup        *ResourceGroup `protobuf:"bytes,1,opt,name=resource_group,json=resourceGroup,proto3" json:"resource_group,omitempty"`
	Error                *Error         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResourceGroupResponse) Reset()         { *m = ResourceGroupResponse{} }
func (m *ResourceGroupResponse) String() string { return proto.CompactTextString(m) }
func (*ResourceGroupResponse) ProtoMessage()    {}
func (*ResourceGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1b72f771c35e3b8, []int{3}
}

func (m *ResourceGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceGroupResponse.Unmarshal(m, b)
}
func (m *ResourceGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceGroupResponse.Marshal(b, m, deterministic)
}
func (m *ResourceGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceGroupResponse.Merge(m, src)
}
func (m *ResourceGroupResponse) XXX_Size() int {
	return xxx_messageInfo_ResourceGroupResponse.Size(m)
}
func (m *ResourceGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceGroupResponse proto.InternalMessageInfo

func (m *ResourceGroupResponse) GetResourceGroup() *ResourceGroup {
	if m != nil {
		return m.ResourceGroup
	}
	return nil
}

func (m *ResourceGroupResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*ResourceGroup)(nil), "pb.ResourceGroup")
	proto.RegisterType((*ResourceGroupSpec)(nil), "pb.ResourceGroupSpec")
	proto.RegisterType((*Resource)(nil), "pb.Resource")
	proto.RegisterType((*ResourceGroupResponse)(nil), "pb.ResourceGroupResponse")
}

func init() { proto.RegisterFile("resource.proto", fileDescriptor_d1b72f771c35e3b8) }

var fileDescriptor_d1b72f771c35e3b8 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xa2, 0x40,
	0x18, 0x5e, 0xf1, 0x23, 0xeb, 0x8b, 0xe2, 0x32, 0xbb, 0x26, 0xac, 0x17, 0x0d, 0x7b, 0x21, 0x1e,
	0x38, 0xb0, 0x97, 0xde, 0x6a, 0xad, 0x8d, 0xf5, 0xd2, 0x03, 0xd5, 0x4b, 0x2f, 0x04, 0xe4, 0x4d,
	0x43, 0xa2, 0x32, 0x19, 0xe0, 0x60, 0xd2, 0x3f, 0xd2, 0x4b, 0x7f, 0x6b, 0xc3, 0xe0, 0x8c, 0xa0,
	0xa6, 0x49, 0xdb, 0x9b, 0x79, 0xde, 0xe7, 0x2b, 0x8f, 0x03, 0x68, 0x0c, 0x93, 0x38, 0x63, 0x6b,
	0xb4, 0x29, 0x8b, 0xd3, 0x98, 0x28, 0x34, 0x18, 0xa8, 0xc8, 0x58, 0xcc, 0x0a, 0x60, 0xd0, 0x17,
	0x84, 0x8c, 0x45, 0xe9, 0x96, 0x6e, 0x0a, 0xd8, 0x7c, 0x55, 0xa0, 0xeb, 0x1e, 0x2e, 0x73, 0x16,
	0x67, 0x94, 0x8c, 0x41, 0x17, 0x54, 0xef, 0x39, 0x47, 0xbc, 0x28, 0x34, 0x6a, 0xa3, 0x9a, 0xd5,
	0x76, 0x7b, 0xac, 0xcc, 0x5c, 0x84, 0xc4, 0x86, 0xdf, 0x27, 0xdc, 0x9d, 0xbf, 0x45, 0x43, 0xe1,
	0x6c, 0xbd, 0xc2, 0x7e, 0xf0, 0xb7, 0x48, 0xa6, 0x40, 0x24, 0x3f, 0x63, 0x91, 0x97, 0x17, 0x49,
	0x8c, 0xfa, 0xa8, 0x66, 0xa9, 0xce, 0x1f, 0x9b, 0x06, 0xb6, 0xa8, 0xb2, 0x62, 0xd1, 0x32, 0xbf,
	0xb9, 0xbf, 0xd8, 0x09, 0x42, 0x08, 0x34, 0x42, 0x4c, 0xd6, 0x46, 0x83, 0x87, 0xf0, 0xdf, 0xc4,
	0x02, 0xc9, 0xf3, 0xd2, 0x3d, 0xc5, 0xbc, 0x72, 0x93, 0xdf, 0xe5, 0x2e, 0xcb, 0x3d, 0xc5, 0x45,
	0x48, 0xc6, 0xd0, 0x16, 0x48, 0x62, 0xb4, 0x46, 0x75, 0x4b, 0x75, 0x3a, 0xe5, 0x60, 0xf7, 0x78,
	0x36, 0xaf, 0x41, 0xaf, 0x4c, 0xf3, 0x48, 0x71, 0xfd, 0x99, 0x79, 0xcc, 0x17, 0xf8, 0x29, 0x0c,
	0xc8, 0x10, 0x54, 0xa9, 0x93, 0x0a, 0x10, 0xd0, 0x22, 0x24, 0xff, 0xa0, 0x2b, 0x09, 0xa5, 0x15,
	0x3b, 0x02, 0xe4, 0x03, 0x5e, 0x4c, 0xaf, 0x5f, 0x4e, 0x67, 0xd0, 0xaf, 0xd4, 0x77, 0x31, 0xa1,
	0xf1, 0x2e, 0x41, 0x72, 0x75, 0x7c, 0x2d, 0x85, 0x09, 0x6f, 0xa3, 0x3a, 0x7a, 0x79, 0x88, 0x42,
	0xd2, 0xad, 0x98, 0x92, 0x21, 0x34, 0xf9, 0x9b, 0xe2, 0xdd, 0x54, 0xa7, 0x9d, 0x0b, 0xee, 0x72,
	0xc0, 0x2d, 0x70, 0xe7, 0x4d, 0x81, 0x9e, 0x70, 0xb8, 0xf7, 0x77, 0xe1, 0x06, 0x19, 0x99, 0x80,
	0x76, 0xcb, 0xd0, 0x4f, 0x51, 0x6e, 0x71, 0x1e, 0x34, 0xf8, 0x7b, 0x9e, 0x7d, 0xa8, 0x6b, 0xfe,
	0x20, 0x37, 0xa0, 0xce, 0x31, 0x95, 0xf2, 0xfe, 0x19, 0x37, 0xff, 0x67, 0x3e, 0xb6, 0x98, 0x80,
	0xb6, 0xa2, 0xe1, 0x77, 0x4a, 0xcc, 0x40, 0x9b, 0xe1, 0x06, 0x4b, 0x0e, 0x5f, 0xe8, 0x31, 0x6d,
	0x3c, 0x29, 0x34, 0x08, 0x5a, 0xfc, 0xe3, 0xfb, 0xff, 0x1e, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xe7,
	0xc2, 0x2c, 0xb6, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResourceHandlerClient is the client API for ResourceHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceHandlerClient interface {
	// resource
	CreateResource(ctx context.Context, in *ResourceGroup, opts ...grpc.CallOption) (*ResourceGroupResponse, error)
	GetResource(ctx context.Context, in *ResourceGroupSpec, opts ...grpc.CallOption) (*ResourceGroupResponse, error)
	UpdateResource(ctx context.Context, in *ResourceGroup, opts ...grpc.CallOption) (*ResourceGroupResponse, error)
	DeleteResource(ctx context.Context, in *ResourceGroupSpec, opts ...grpc.CallOption) (*ResourceGroupResponse, error)
}

type resourceHandlerClient struct {
	cc *grpc.ClientConn
}

func NewResourceHandlerClient(cc *grpc.ClientConn) ResourceHandlerClient {
	return &resourceHandlerClient{cc}
}

func (c *resourceHandlerClient) CreateResource(ctx context.Context, in *ResourceGroup, opts ...grpc.CallOption) (*ResourceGroupResponse, error) {
	out := new(ResourceGroupResponse)
	err := c.cc.Invoke(ctx, "/pb.ResourceHandler/CreateResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceHandlerClient) GetResource(ctx context.Context, in *ResourceGroupSpec, opts ...grpc.CallOption) (*ResourceGroupResponse, error) {
	out := new(ResourceGroupResponse)
	err := c.cc.Invoke(ctx, "/pb.ResourceHandler/GetResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceHandlerClient) UpdateResource(ctx context.Context, in *ResourceGroup, opts ...grpc.CallOption) (*ResourceGroupResponse, error) {
	out := new(ResourceGroupResponse)
	err := c.cc.Invoke(ctx, "/pb.ResourceHandler/UpdateResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceHandlerClient) DeleteResource(ctx context.Context, in *ResourceGroupSpec, opts ...grpc.CallOption) (*ResourceGroupResponse, error) {
	out := new(ResourceGroupResponse)
	err := c.cc.Invoke(ctx, "/pb.ResourceHandler/DeleteResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceHandlerServer is the server API for ResourceHandler service.
type ResourceHandlerServer interface {
	// resource
	CreateResource(context.Context, *ResourceGroup) (*ResourceGroupResponse, error)
	GetResource(context.Context, *ResourceGroupSpec) (*ResourceGroupResponse, error)
	UpdateResource(context.Context, *ResourceGroup) (*ResourceGroupResponse, error)
	DeleteResource(context.Context, *ResourceGroupSpec) (*ResourceGroupResponse, error)
}

func RegisterResourceHandlerServer(s *grpc.Server, srv ResourceHandlerServer) {
	s.RegisterService(&_ResourceHandler_serviceDesc, srv)
}

func _ResourceHandler_CreateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceHandlerServer).CreateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceHandler/CreateResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceHandlerServer).CreateResource(ctx, req.(*ResourceGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceHandler_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceHandlerServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceHandler/GetResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceHandlerServer).GetResource(ctx, req.(*ResourceGroupSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceHandler_UpdateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceHandlerServer).UpdateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceHandler/UpdateResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceHandlerServer).UpdateResource(ctx, req.(*ResourceGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceHandler_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceHandlerServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceHandler/DeleteResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceHandlerServer).DeleteResource(ctx, req.(*ResourceGroupSpec))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ResourceHandler",
	HandlerType: (*ResourceHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateResource",
			Handler:    _ResourceHandler_CreateResource_Handler,
		},
		{
			MethodName: "GetResource",
			Handler:    _ResourceHandler_GetResource_Handler,
		},
		{
			MethodName: "UpdateResource",
			Handler:    _ResourceHandler_UpdateResource_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _ResourceHandler_DeleteResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource.proto",
}
