// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// resource group
type ResourceGroup struct {
	ResourceGroupId   string            `protobuf:"bytes,1,opt,name=resource_group_id" json:"resource_group_id,omitempty"`
	ResourceGroupName string            `protobuf:"bytes,2,opt,name=resource_group_name" json:"resource_group_name,omitempty"`
	ResourceUriTmpls  *ResourceUriTmpls `protobuf:"bytes,3,opt,name=resource_uri_tmpls" json:"resource_uri_tmpls,omitempty"`
	Desc              string            `protobuf:"bytes,4,opt,name=desc" json:"desc,omitempty"`
	ResourceTypeId    string            `protobuf:"bytes,5,opt,name=resource_type_id" json:"resource_type_id,omitempty"`
	Resources         []*Resource       `protobuf:"bytes,6,rep,name=resources" json:"resources,omitempty"`
}

func (m *ResourceGroup) Reset()                    { *m = ResourceGroup{} }
func (m *ResourceGroup) String() string            { return proto.CompactTextString(m) }
func (*ResourceGroup) ProtoMessage()               {}
func (*ResourceGroup) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *ResourceGroup) GetResourceGroupId() string {
	if m != nil {
		return m.ResourceGroupId
	}
	return ""
}

func (m *ResourceGroup) GetResourceGroupName() string {
	if m != nil {
		return m.ResourceGroupName
	}
	return ""
}

func (m *ResourceGroup) GetResourceUriTmpls() *ResourceUriTmpls {
	if m != nil {
		return m.ResourceUriTmpls
	}
	return nil
}

func (m *ResourceGroup) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ResourceGroup) GetResourceTypeId() string {
	if m != nil {
		return m.ResourceTypeId
	}
	return ""
}

func (m *ResourceGroup) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type ResourceGroupSpec struct {
	ResourceGroupId string `protobuf:"bytes,1,opt,name=resource_group_id" json:"resource_group_id,omitempty"`
}

func (m *ResourceGroupSpec) Reset()                    { *m = ResourceGroupSpec{} }
func (m *ResourceGroupSpec) String() string            { return proto.CompactTextString(m) }
func (*ResourceGroupSpec) ProtoMessage()               {}
func (*ResourceGroupSpec) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *ResourceGroupSpec) GetResourceGroupId() string {
	if m != nil {
		return m.ResourceGroupId
	}
	return ""
}

type Resource struct {
	ResourceId      string `protobuf:"bytes,1,opt,name=resource_id" json:"resource_id,omitempty"`
	ResourceName    string `protobuf:"bytes,2,opt,name=resource_name" json:"resource_name,omitempty"`
	ResourceGroupId string `protobuf:"bytes,3,opt,name=resource_group_id" json:"resource_group_id,omitempty"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

func (m *Resource) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *Resource) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *Resource) GetResourceGroupId() string {
	if m != nil {
		return m.ResourceGroupId
	}
	return ""
}

type ResourceGroupResponse struct {
	ResourceGroup *ResourceGroup `protobuf:"bytes,1,opt,name=resource_group" json:"resource_group,omitempty"`
	Error         *Error         `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *ResourceGroupResponse) Reset()                    { *m = ResourceGroupResponse{} }
func (m *ResourceGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*ResourceGroupResponse) ProtoMessage()               {}
func (*ResourceGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{3} }

func (m *ResourceGroupResponse) GetResourceGroup() *ResourceGroup {
	if m != nil {
		return m.ResourceGroup
	}
	return nil
}

func (m *ResourceGroupResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*ResourceGroup)(nil), "pb.ResourceGroup")
	proto.RegisterType((*ResourceGroupSpec)(nil), "pb.ResourceGroupSpec")
	proto.RegisterType((*Resource)(nil), "pb.Resource")
	proto.RegisterType((*ResourceGroupResponse)(nil), "pb.ResourceGroupResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ResourceHandler service

type ResourceHandlerClient interface {
	// resource
	CreateResource(ctx context.Context, in *ResourceGroup, opts ...grpc.CallOption) (*ResourceGroupResponse, error)
	GetResource(ctx context.Context, in *ResourceGroupSpec, opts ...grpc.CallOption) (*ResourceGroupResponse, error)
	UpdateResource(ctx context.Context, in *ResourceGroup, opts ...grpc.CallOption) (*ResourceGroupResponse, error)
	DeleteResource(ctx context.Context, in *ResourceGroupSpec, opts ...grpc.CallOption) (*ResourceGroupResponse, error)
}

type resourceHandlerClient struct {
	cc *grpc.ClientConn
}

func NewResourceHandlerClient(cc *grpc.ClientConn) ResourceHandlerClient {
	return &resourceHandlerClient{cc}
}

func (c *resourceHandlerClient) CreateResource(ctx context.Context, in *ResourceGroup, opts ...grpc.CallOption) (*ResourceGroupResponse, error) {
	out := new(ResourceGroupResponse)
	err := grpc.Invoke(ctx, "/pb.ResourceHandler/CreateResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceHandlerClient) GetResource(ctx context.Context, in *ResourceGroupSpec, opts ...grpc.CallOption) (*ResourceGroupResponse, error) {
	out := new(ResourceGroupResponse)
	err := grpc.Invoke(ctx, "/pb.ResourceHandler/GetResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceHandlerClient) UpdateResource(ctx context.Context, in *ResourceGroup, opts ...grpc.CallOption) (*ResourceGroupResponse, error) {
	out := new(ResourceGroupResponse)
	err := grpc.Invoke(ctx, "/pb.ResourceHandler/UpdateResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceHandlerClient) DeleteResource(ctx context.Context, in *ResourceGroupSpec, opts ...grpc.CallOption) (*ResourceGroupResponse, error) {
	out := new(ResourceGroupResponse)
	err := grpc.Invoke(ctx, "/pb.ResourceHandler/DeleteResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ResourceHandler service

type ResourceHandlerServer interface {
	// resource
	CreateResource(context.Context, *ResourceGroup) (*ResourceGroupResponse, error)
	GetResource(context.Context, *ResourceGroupSpec) (*ResourceGroupResponse, error)
	UpdateResource(context.Context, *ResourceGroup) (*ResourceGroupResponse, error)
	DeleteResource(context.Context, *ResourceGroupSpec) (*ResourceGroupResponse, error)
}

func RegisterResourceHandlerServer(s *grpc.Server, srv ResourceHandlerServer) {
	s.RegisterService(&_ResourceHandler_serviceDesc, srv)
}

func _ResourceHandler_CreateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceHandlerServer).CreateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceHandler/CreateResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceHandlerServer).CreateResource(ctx, req.(*ResourceGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceHandler_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceHandlerServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceHandler/GetResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceHandlerServer).GetResource(ctx, req.(*ResourceGroupSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceHandler_UpdateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceHandlerServer).UpdateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceHandler/UpdateResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceHandlerServer).UpdateResource(ctx, req.(*ResourceGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceHandler_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceGroupSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceHandlerServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceHandler/DeleteResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceHandlerServer).DeleteResource(ctx, req.(*ResourceGroupSpec))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ResourceHandler",
	HandlerType: (*ResourceHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateResource",
			Handler:    _ResourceHandler_CreateResource_Handler,
		},
		{
			MethodName: "GetResource",
			Handler:    _ResourceHandler_GetResource_Handler,
		},
		{
			MethodName: "UpdateResource",
			Handler:    _ResourceHandler_UpdateResource_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _ResourceHandler_DeleteResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource.proto",
}

func init() { proto.RegisterFile("resource.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0xfd, 0x5a, 0x7e, 0xf2, 0x71, 0x07, 0xaa, 0x0c, 0x36, 0x19, 0x70, 0x21, 0xe9, 0x0a, 0x37,
	0x8d, 0xa9, 0x2f, 0x80, 0x8a, 0xc1, 0xad, 0x28, 0x1b, 0x63, 0x42, 0x28, 0xbd, 0x31, 0x4d, 0x80,
	0x4e, 0x66, 0xda, 0x85, 0x2f, 0xe3, 0xc3, 0xf8, 0x64, 0x66, 0xa6, 0xce, 0x58, 0xc4, 0xb0, 0xd0,
	0xed, 0x39, 0xe7, 0x9e, 0x73, 0xcf, 0xdc, 0x01, 0x4f, 0xa0, 0xcc, 0x0a, 0xb1, 0xc2, 0x90, 0x8b,
	0x2c, 0xcf, 0xa8, 0xcb, 0xe3, 0x01, 0x41, 0x21, 0x32, 0x51, 0x02, 0x03, 0xdf, 0x08, 0x0a, 0x91,
	0xe6, 0x1b, 0xbe, 0x2e, 0xe1, 0xe0, 0xdd, 0x81, 0xce, 0xec, 0x93, 0x99, 0x8a, 0xac, 0xe0, 0xb4,
	0x0f, 0x5d, 0x23, 0x5d, 0xbc, 0x28, 0x64, 0x91, 0x26, 0xcc, 0x19, 0x3a, 0xa3, 0x16, 0x3d, 0x85,
	0xde, 0x37, 0x6a, 0xbb, 0xdc, 0x20, 0x73, 0x35, 0x79, 0x01, 0xd4, 0x92, 0x85, 0x48, 0x17, 0x2a,
	0x44, 0xb2, 0xda, 0xd0, 0x19, 0x91, 0xe8, 0x24, 0xe4, 0x71, 0x68, 0x62, 0xe6, 0x22, 0x7d, 0x54,
	0x1c, 0x6d, 0x43, 0x3d, 0x41, 0xb9, 0x62, 0x75, 0x3d, 0xcf, 0xe0, 0xd8, 0xce, 0xe7, 0xaf, 0x1c,
	0x55, 0x6c, 0x43, 0x33, 0x67, 0xd0, 0x32, 0x8c, 0x64, 0xcd, 0x61, 0x6d, 0x44, 0xa2, 0x76, 0xd5,
	0x30, 0x08, 0xa1, 0xbb, 0xd3, 0xe1, 0x81, 0xe3, 0xea, 0x40, 0x8f, 0xe0, 0x1e, 0xfe, 0x1b, 0x3d,
	0xed, 0x01, 0xb1, 0x32, 0x5b, 0xd4, 0x87, 0x8e, 0x05, 0x2b, 0x15, 0x7f, 0xb4, 0xac, 0x69, 0xcb,
	0x67, 0xf0, 0x77, 0x56, 0x98, 0xa1, 0xe4, 0xd9, 0x56, 0x22, 0x3d, 0xff, 0x3a, 0x4d, 0x39, 0xa3,
	0x23, 0x48, 0xd4, 0xad, 0x36, 0x28, 0x5f, 0x9e, 0x41, 0x43, 0x5f, 0x4c, 0xa7, 0x91, 0xa8, 0xa5,
	0x14, 0xb7, 0x0a, 0x88, 0xde, 0x5c, 0x38, 0x32, 0xda, 0xbb, 0xe5, 0x36, 0x59, 0xa3, 0xa0, 0x63,
	0xf0, 0x6e, 0x04, 0x2e, 0x73, 0xb4, 0x55, 0xf6, 0x2d, 0x07, 0xfd, 0x3d, 0xc8, 0x2c, 0x16, 0xfc,
	0xa3, 0x57, 0x40, 0xa6, 0x98, 0xdb, 0x71, 0x7f, 0x4f, 0xab, 0xde, 0xf1, 0xb0, 0xc5, 0x18, 0xbc,
	0x39, 0x4f, 0xfe, 0xb2, 0xc4, 0x04, 0xbc, 0x09, 0xae, 0xb1, 0xe2, 0xf0, 0x8b, 0x3d, 0xae, 0xeb,
	0x4f, 0x2e, 0x8f, 0xe3, 0xa6, 0xfe, 0xd3, 0x97, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x96,
	0xdd, 0x44, 0x0d, 0x03, 0x00, 0x00,
}
