apiVersion: v1
kind: Service
metadata:
  name: alerting-dispatcher-server
  namespace: kubesphere-monitoring-system
spec:
  selector:
    app: alerting-dispatcher
  ports:
  - name:  alerting-dispatcher-server
    protocol: TCP
    port: 50000
    targetPort: 50000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: alerting-dispatcher
  name: alerting-dispatcher
  namespace: kubesphere-monitoring-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alerting-dispatcher
  template:
    metadata:
      labels:
        app: alerting-dispatcher
    spec:
      containers:
      - command:
        - /alerting/dispatcher
        - -database=alert
        - -etcd_addr=http://alerting-etcd.kubesphere-monitoring-system.svc:2379
        - -mysql=alerting-db.kubesphere-monitoring-system.svc
		- -mysql_port=3306
        - -user=root
        - -password=password
        image: carmanzhang/alerting-dev:latest
        imagePullPolicy: IfNotPresent
        name: alerting-dispatcher
        ports:
        - containerPort: 50000
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 200Mi
