apiVersion: v1
kind: Service
metadata:
  name: alerting-executor-server
  namespace: kubesphere-monitoring-system
spec:
  selector:
    app: alerting-executor
  ports:
  - name:  alerting-executor-server
    protocol: TCP
    port: 50001
    targetPort: 50001
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: alerting-executor
  name: alerting-executor
  namespace: kubesphere-monitoring-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alerting-executor
  serviceName: alerting-executor-server
  template:
    metadata:
      labels:
        app: alerting-executor
    spec:
      containers:
      - args:
        - -database=alert
        - -etcd_addr=http://alerting-etcd.kubesphere-monitoring-system.svc:2379
        - -mysql=alerting-db.kubesphere-monitoring-system.svc
        - -mysql_port=3306
        - -user=root
        - -password=password
        command:
        - /alerting/executor
        image: carmanzhang/alerting-dev:latest
        imagePullPolicy: Always
        name: alerting-executor
#        livenessProbe:
#          failureThreshold: 6
#          httpGet:
#            path: /-/healthy
#            port: web
#            scheme: HTTP
#          periodSeconds: 5
#          successThreshold: 1
#          timeoutSeconds: 3
#        readinessProbe:
#          failureThreshold: 120
#          httpGet:
#            path: /-/ready
#            port: web
#            scheme: HTTP
#          periodSeconds: 5
#          successThreshold: 1
#          timeoutSeconds: 3
        ports:
        - containerPort: 50001
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 200Mi