// Code generated by protoc-gen-go. DO NOT EDIT.
// source: severity.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Severity
type SeveritySpec struct {
	SeverityId           string   `protobuf:"bytes,1,opt,name=severity_id,json=severityId,proto3" json:"severity_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName          string   `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeveritySpec) Reset()         { *m = SeveritySpec{} }
func (m *SeveritySpec) String() string { return proto.CompactTextString(m) }
func (*SeveritySpec) ProtoMessage()    {}
func (*SeveritySpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01ec8b8a50f5055, []int{0}
}

func (m *SeveritySpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeveritySpec.Unmarshal(m, b)
}
func (m *SeveritySpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeveritySpec.Marshal(b, m, deterministic)
}
func (m *SeveritySpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeveritySpec.Merge(m, src)
}
func (m *SeveritySpec) XXX_Size() int {
	return xxx_messageInfo_SeveritySpec.Size(m)
}
func (m *SeveritySpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SeveritySpec.DiscardUnknown(m)
}

var xxx_messageInfo_SeveritySpec proto.InternalMessageInfo

func (m *SeveritySpec) GetSeverityId() string {
	if m != nil {
		return m.SeverityId
	}
	return ""
}

func (m *SeveritySpec) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *SeveritySpec) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

type Severity struct {
	SeverityId           string   `protobuf:"bytes,1,opt,name=severity_id,json=severityId,proto3" json:"severity_id,omitempty"`
	SeverityCh           string   `protobuf:"bytes,2,opt,name=severity_ch,json=severityCh,proto3" json:"severity_ch,omitempty"`
	SeverityEn           string   `protobuf:"bytes,3,opt,name=severity_en,json=severityEn,proto3" json:"severity_en,omitempty"`
	ProductId            string   `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Severity) Reset()         { *m = Severity{} }
func (m *Severity) String() string { return proto.CompactTextString(m) }
func (*Severity) ProtoMessage()    {}
func (*Severity) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01ec8b8a50f5055, []int{1}
}

func (m *Severity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Severity.Unmarshal(m, b)
}
func (m *Severity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Severity.Marshal(b, m, deterministic)
}
func (m *Severity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Severity.Merge(m, src)
}
func (m *Severity) XXX_Size() int {
	return xxx_messageInfo_Severity.Size(m)
}
func (m *Severity) XXX_DiscardUnknown() {
	xxx_messageInfo_Severity.DiscardUnknown(m)
}

var xxx_messageInfo_Severity proto.InternalMessageInfo

func (m *Severity) GetSeverityId() string {
	if m != nil {
		return m.SeverityId
	}
	return ""
}

func (m *Severity) GetSeverityCh() string {
	if m != nil {
		return m.SeverityCh
	}
	return ""
}

func (m *Severity) GetSeverityEn() string {
	if m != nil {
		return m.SeverityEn
	}
	return ""
}

func (m *Severity) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type SeverityResponse struct {
	Severity             *Severity `protobuf:"bytes,1,opt,name=Severity,proto3" json:"Severity,omitempty"`
	Error                *Error    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SeverityResponse) Reset()         { *m = SeverityResponse{} }
func (m *SeverityResponse) String() string { return proto.CompactTextString(m) }
func (*SeverityResponse) ProtoMessage()    {}
func (*SeverityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01ec8b8a50f5055, []int{2}
}

func (m *SeverityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeverityResponse.Unmarshal(m, b)
}
func (m *SeverityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeverityResponse.Marshal(b, m, deterministic)
}
func (m *SeverityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeverityResponse.Merge(m, src)
}
func (m *SeverityResponse) XXX_Size() int {
	return xxx_messageInfo_SeverityResponse.Size(m)
}
func (m *SeverityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SeverityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SeverityResponse proto.InternalMessageInfo

func (m *SeverityResponse) GetSeverity() *Severity {
	if m != nil {
		return m.Severity
	}
	return nil
}

func (m *SeverityResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type SeveritiesResponse struct {
	Severity             []*Severity `protobuf:"bytes,1,rep,name=Severity,proto3" json:"Severity,omitempty"`
	Error                *Error      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SeveritiesResponse) Reset()         { *m = SeveritiesResponse{} }
func (m *SeveritiesResponse) String() string { return proto.CompactTextString(m) }
func (*SeveritiesResponse) ProtoMessage()    {}
func (*SeveritiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01ec8b8a50f5055, []int{3}
}

func (m *SeveritiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeveritiesResponse.Unmarshal(m, b)
}
func (m *SeveritiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeveritiesResponse.Marshal(b, m, deterministic)
}
func (m *SeveritiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeveritiesResponse.Merge(m, src)
}
func (m *SeveritiesResponse) XXX_Size() int {
	return xxx_messageInfo_SeveritiesResponse.Size(m)
}
func (m *SeveritiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SeveritiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SeveritiesResponse proto.InternalMessageInfo

func (m *SeveritiesResponse) GetSeverity() []*Severity {
	if m != nil {
		return m.Severity
	}
	return nil
}

func (m *SeveritiesResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*SeveritySpec)(nil), "pb.SeveritySpec")
	proto.RegisterType((*Severity)(nil), "pb.Severity")
	proto.RegisterType((*SeverityResponse)(nil), "pb.SeverityResponse")
	proto.RegisterType((*SeveritiesResponse)(nil), "pb.SeveritiesResponse")
}

func init() { proto.RegisterFile("severity.proto", fileDescriptor_c01ec8b8a50f5055) }

var fileDescriptor_c01ec8b8a50f5055 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0x9b, 0xb6, 0xdf, 0x87, 0x99, 0x0d, 0xb1, 0x2c, 0x22, 0xa5, 0x20, 0xea, 0x9e, 0x7a,
	0xca, 0x21, 0x42, 0x41, 0x8f, 0xd6, 0xa2, 0xbd, 0x78, 0x48, 0xf1, 0x22, 0x48, 0x49, 0xb2, 0x03,
	0x0d, 0xb4, 0xc9, 0xba, 0x89, 0x82, 0xff, 0xc1, 0x1f, 0xec, 0x51, 0xb2, 0xdd, 0x8d, 0x9b, 0x42,
	0x15, 0xf1, 0xfa, 0xce, 0x33, 0xfb, 0xbc, 0x2c, 0x03, 0x7e, 0x89, 0xaf, 0x28, 0xb3, 0xea, 0x2d,
	0x10, 0xb2, 0xa8, 0x0a, 0xda, 0x15, 0xc9, 0x88, 0xa0, 0x94, 0x85, 0xdc, 0x06, 0xec, 0x19, 0xbc,
	0x85, 0x46, 0x16, 0x02, 0x53, 0x7a, 0x0a, 0xc4, 0xac, 0x2c, 0x33, 0x3e, 0x74, 0xce, 0x9c, 0xb1,
	0x1b, 0x81, 0x89, 0xe6, 0x9c, 0x9e, 0x00, 0x08, 0x59, 0xf0, 0x97, 0xb4, 0xaa, 0xe7, 0x5d, 0x35,
	0x77, 0x75, 0x32, 0xe7, 0xf4, 0x1c, 0x3c, 0x33, 0xce, 0xe3, 0x0d, 0x0e, 0x7b, 0x0a, 0x20, 0x3a,
	0xbb, 0x8f, 0x37, 0xc8, 0xde, 0x1d, 0x38, 0x30, 0xce, 0x9f, 0x7d, 0x36, 0x90, 0xae, 0xb4, 0xb0,
	0x01, 0xa6, 0xab, 0x16, 0x80, 0xb9, 0x16, 0x36, 0xc0, 0x2c, 0xdf, 0x69, 0xdc, 0xdf, 0x69, 0xcc,
	0x9e, 0x60, 0x60, 0xda, 0x44, 0x58, 0x8a, 0x22, 0x2f, 0x91, 0x8e, 0xbf, 0x1a, 0xaa, 0x4a, 0x24,
	0xf4, 0x02, 0x91, 0x04, 0x0d, 0x67, 0xf7, 0xff, 0xa7, 0xbe, 0x53, 0x15, 0x23, 0xa1, 0x5b, 0x63,
	0xb3, 0x3a, 0x88, 0xb6, 0x39, 0x5b, 0x02, 0xd5, 0x70, 0x86, 0xe5, 0x1e, 0x41, 0xef, 0x0f, 0x82,
	0xf0, 0xc3, 0x81, 0x43, 0x43, 0xdf, 0xc5, 0x39, 0x5f, 0xa3, 0xa4, 0x13, 0xf0, 0xa7, 0x12, 0xe3,
	0x0a, 0x9b, 0x67, 0x5a, 0xcf, 0x8f, 0x8e, 0x5a, 0x32, 0x5d, 0x8a, 0x75, 0xe8, 0x15, 0xf8, 0x37,
	0xb8, 0x46, 0x6b, 0x6f, 0x60, 0x93, 0xf5, 0x85, 0xec, 0xdd, 0x9d, 0x80, 0xff, 0x20, 0xf8, 0xef,
	0x9d, 0x97, 0x40, 0x6e, 0xb1, 0xfa, 0x46, 0x78, 0x6c, 0x25, 0xd6, 0x1f, 0xb2, 0xce, 0x75, 0xff,
	0xb1, 0x2b, 0x92, 0xe4, 0xbf, 0xba, 0xe4, 0x8b, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0x4e,
	0xf4, 0x58, 0xec, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SeverityHandlerClient is the client API for SeverityHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SeverityHandlerClient interface {
	// Severity
	CreateSeverity(ctx context.Context, in *Severity, opts ...grpc.CallOption) (*SeverityResponse, error)
	DeleteSeverity(ctx context.Context, in *SeveritySpec, opts ...grpc.CallOption) (*SeverityResponse, error)
	UpdateSeverity(ctx context.Context, in *Severity, opts ...grpc.CallOption) (*SeverityResponse, error)
	GetSeverity(ctx context.Context, in *SeveritySpec, opts ...grpc.CallOption) (*SeveritiesResponse, error)
}

type severityHandlerClient struct {
	cc *grpc.ClientConn
}

func NewSeverityHandlerClient(cc *grpc.ClientConn) SeverityHandlerClient {
	return &severityHandlerClient{cc}
}

func (c *severityHandlerClient) CreateSeverity(ctx context.Context, in *Severity, opts ...grpc.CallOption) (*SeverityResponse, error) {
	out := new(SeverityResponse)
	err := c.cc.Invoke(ctx, "/pb.SeverityHandler/CreateSeverity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *severityHandlerClient) DeleteSeverity(ctx context.Context, in *SeveritySpec, opts ...grpc.CallOption) (*SeverityResponse, error) {
	out := new(SeverityResponse)
	err := c.cc.Invoke(ctx, "/pb.SeverityHandler/DeleteSeverity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *severityHandlerClient) UpdateSeverity(ctx context.Context, in *Severity, opts ...grpc.CallOption) (*SeverityResponse, error) {
	out := new(SeverityResponse)
	err := c.cc.Invoke(ctx, "/pb.SeverityHandler/UpdateSeverity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *severityHandlerClient) GetSeverity(ctx context.Context, in *SeveritySpec, opts ...grpc.CallOption) (*SeveritiesResponse, error) {
	out := new(SeveritiesResponse)
	err := c.cc.Invoke(ctx, "/pb.SeverityHandler/GetSeverity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeverityHandlerServer is the server API for SeverityHandler service.
type SeverityHandlerServer interface {
	// Severity
	CreateSeverity(context.Context, *Severity) (*SeverityResponse, error)
	DeleteSeverity(context.Context, *SeveritySpec) (*SeverityResponse, error)
	UpdateSeverity(context.Context, *Severity) (*SeverityResponse, error)
	GetSeverity(context.Context, *SeveritySpec) (*SeveritiesResponse, error)
}

func RegisterSeverityHandlerServer(s *grpc.Server, srv SeverityHandlerServer) {
	s.RegisterService(&_SeverityHandler_serviceDesc, srv)
}

func _SeverityHandler_CreateSeverity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Severity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeverityHandlerServer).CreateSeverity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SeverityHandler/CreateSeverity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeverityHandlerServer).CreateSeverity(ctx, req.(*Severity))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeverityHandler_DeleteSeverity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeveritySpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeverityHandlerServer).DeleteSeverity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SeverityHandler/DeleteSeverity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeverityHandlerServer).DeleteSeverity(ctx, req.(*SeveritySpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeverityHandler_UpdateSeverity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Severity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeverityHandlerServer).UpdateSeverity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SeverityHandler/UpdateSeverity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeverityHandlerServer).UpdateSeverity(ctx, req.(*Severity))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeverityHandler_GetSeverity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeveritySpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeverityHandlerServer).GetSeverity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SeverityHandler/GetSeverity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeverityHandlerServer).GetSeverity(ctx, req.(*SeveritySpec))
	}
	return interceptor(ctx, in, info, handler)
}

var _SeverityHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SeverityHandler",
	HandlerType: (*SeverityHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSeverity",
			Handler:    _SeverityHandler_CreateSeverity_Handler,
		},
		{
			MethodName: "DeleteSeverity",
			Handler:    _SeverityHandler_DeleteSeverity_Handler,
		},
		{
			MethodName: "UpdateSeverity",
			Handler:    _SeverityHandler_UpdateSeverity_Handler,
		},
		{
			MethodName: "GetSeverity",
			Handler:    _SeverityHandler_GetSeverity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "severity.proto",
}
